version: '3'
services:
  quart:
    container_name: quart_app
    build: ./
    volumes:
      - ./content:/deploy/wiki_app/content
      - ./config:/deploy/wiki_app/config
    ports:
      - "5000:5000"